import type { MetadataRoute } from 'next';

const routes = [
  '',
  '/assessments',
  '/assessments/adhd',
  '/assessments/autism',
  '/assessments/adhd-autism',
  '/assessments/dyslexia',
  '/assessments/dyscalculia',
  '/assessments/dyspraxia',
  '/adults',
  '/adults/adhd',
  '/adults/autism',
  '/adults/dyslexia',
  '/adults/adhd-autism',
  '/children',
  '/children/adhd',
  '/children/autism',
  '/children/dyslexia',
  '/children/adhd-autism',
  '/support',
  '/support/adhd-coaching',
  '/support/autism-coaching',
  '/support/executive-function',
  '/support/learning-support',
  '/support/education-support',
  '/support/behaviour-support',
  '/support/workplace-support',
  '/support/therapy-wellbeing',
  '/support/post-diagnostic',
  '/support/parent-family',
  '/how-it-works',
  '/why-fairneuro',
  '/why-fairneuro/our-standards',
  '/about',
  '/contact',
  '/faqs',
  '/resources',
  '/resources/preparing-for-your-assessment',
  '/resources/your-report-explained',
  '/screener',
  '/screener/adhd',
  '/screener/autism',
  '/screener/dyslexia',
  '/screener/general',
  '/professional-referrals',
  '/schools',
  '/employers',
  '/clinical-care',
  '/book-consultation',
  '/privacy-policy',
  '/terms',
  '/cookies',
  '/complaints',
];

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://fairneuro.com';
  return routes.map((route) => ({
    url: `${base}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' ? 'weekly' : 'monthly',
    priority: route === '' ? 1 : route.split('/').length === 2 ? 0.8 : 0.6,
  }));
}
